CREATE TABLE IF NOT EXISTS courses (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS profiles (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS answers (
    id BIGSERIAL PRIMARY KEY,
    message VARCHAR(100) NOT NULL,
    creation_date DATE NOT NULL DEFAULT CURRENT_DATE,
    solution VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS topics (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    message VARCHAR(100) NOT NULL,
    creation_date DATE NOT NULL DEFAULT CURRENT_DATE,
    status SMALLINT DEFAULT 1 CHECK (status IN (0,1))
);